<a href="https://colab.research.google.com/github/shazzad-hasan/pytorch-101/blob/main/foundation_of_pytorch/autograd_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# instantiate two tensors
tensor1 = torch.Tensor([[1, 2, 3],
                        [4, 5, 6]])

tensor2 = torch.Tensor([[4, 5, 6],
                        [10, 11, 12]])

print(tensor1)
print()
print(tensor2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

tensor([[ 4.,  5.,  6.],
        [10., 11., 12.]])


### requirs_grad

When true this track computations for a tensor in the forward phase and will calculate gradients (with respact to a scalar e.g., loss) for this tensor in the backward phase.

In [ ]:
tensor1.requires_grad

False

In [ ]:
tensor2.requires_grad

False

In [ ]:
# enable track history on this tensor
tensor1.requires_grad_()

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [ ]:
tensor1.requires_grad

True

In [ ]:
tensor2.requires_grad

False

In [ ]:
# let's check if gradients are available yet
print(tensor1.grad)

None


In [ ]:
# 
print(tensor1.grad_fn)

None


In [ ]:
output_tensor = tensor1 * tensor2

In [ ]:
output_tensor.requires_grad

True

In [ ]:
output_tensor.grad

/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:477.)
  return self._grad


In [ ]:
output_tensor.grad_fn

In [ ]:
print(tensor1.grad_fn)

None


In [ ]:
output_tensor = (tensor1 * tensor2).mean()

output_tensor.grad_fn

In [ ]:
print(tensor1.grad)

None


In [ ]:
output_tensor.backward()

In [ ]:
tensor1.grad

tensor([[0.6667, 0.8333, 1.0000],
        [1.6667, 1.8333, 2.0000]])

In [ ]:
tensor1.grad.shape, tensor2.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [ ]:
print(tensor2.grad)

None


In [ ]:
print(output_tensor.grad)

None


/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:477.)
  return self._grad


In [ ]:
with torch.no_grad():
  new_tensor = tensor1 * 3
  print("new tensor = ", new_tensor)
  print("requires_grad for tensor = ", tensor1.requires_grad)
  print("requires_grad for tensor = ", tensor2.requires_grad)
  print("requires_grad for new_tensor = ", new_tensor.requires_grad)

new tensor =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
requires_grad for tensor =  True
requires_grad for tensor =  False
requires_grad for new_tensor =  False


In [ ]:
def calculate(t):
  return t * 2

@torch.no_grad()
def calculate_with_no_grad(t):
  return t * 2

In [ ]:
result_tensor = calculate(tensor1)

print(result_tensor)
print(result_tensor.requires_grad)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], grad_fn=<MulBackward0>)
True


In [ ]:
result_tensor_no_grad = calculate_with_no_grad(tensor1)

print(result_tensor_no_grad)
print(result_tensor_no_grad.requires_grad)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
False


In [ ]:
with torch.no_grad():

  new_tensor_no_grad = tensor1 * 3
  print("new_tensor_no_grad = ", new_tensor_no_grad)

  with torch.enable_grad():
    new_tensor_grad = tensor1 * 3
    print("new_tensor_grad = ", new_tensor_grad)

new_tensor_no_grad =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
new_tensor_grad =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)


In [ ]:
tensor_one = torch.tensor([[1.0, 2.0],
                           [3.0, 4.0]], requires_grad = True)

tensor_one

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [ ]:
tensor_two = torch.Tensor([[5, 6],
                           [7, 8]])
tensor_two

tensor([[5., 6.],
        [7., 8.]])

In [ ]:
tensor_one.requires_grad

True

In [ ]:
tensor_two.requires_grad

False

In [ ]:
final_tensor = (tensor_one + tensor_two).mean()
final_tensor

tensor(9., grad_fn=<MeanBackward0>)

In [ ]:
final_tensor.requires_grad

True

In [ ]:
print(tensor_one.grad)

None


In [ ]:
print(tensor_two.grad)

None


In [ ]:
final_tensor.backward()

print(tensor_one.grad)
print()
print(tensor_two.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])

None


In [ ]:
detached_tensor = tensor_one.detach()

detached_tensor

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
tensor_one

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [ ]:
mean_tensor = (tensor_one + detached_tensor).mean()

mean_tensor.backward()

In [ ]:
tensor_one.grad

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [ ]:
print(detached_tensor.grad)

None
