<a href="https://colab.research.google.com/github/shazzad-hasan/practice-deep-learning-with-pytorch/blob/main/foundation_of_pytorch/conversion_between_pytorch_and_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
tensor = torch.rand(4, 3)
tensor

tensor([[0.1527, 0.3162, 0.1837],
        [0.0620, 0.3754, 0.2011],
        [0.4137, 0.5115, 0.0567],
        [0.6296, 0.6311, 0.3685]])

In [ ]:
type(tensor)

torch.Tensor

In [ ]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.15268868, 0.31622583, 0.18374586],
       [0.0619927 , 0.37538743, 0.20113534],
       [0.4137286 , 0.51152843, 0.05672914],
       [0.62960297, 0.6310672 , 0.36851227]], dtype=float32)

In [ ]:
type(numpy_from_tensor)

numpy.ndarray

In [ ]:
torch.is_tensor(tensor)

True

In [ ]:
numpy_from_tensor[0, 0] = 100.0
numpy_from_tensor

array([[1.0000000e+02, 3.1622583e-01, 1.8374586e-01],
       [6.1992705e-02, 3.7538743e-01, 2.0113534e-01],
       [4.1372859e-01, 5.1152843e-01, 5.6729138e-02],
       [6.2960297e-01, 6.3106722e-01, 3.6851227e-01]], dtype=float32)

In [ ]:
tensor

tensor([[1.0000e+02, 3.1623e-01, 1.8375e-01],
        [6.1993e-02, 3.7539e-01, 2.0114e-01],
        [4.1373e-01, 5.1153e-01, 5.6729e-02],
        [6.2960e-01, 6.3107e-01, 3.6851e-01]])

In [ ]:
numpy_arr = np.array([[1.0, 2.0, 3.0],
                      [10.0, 20.0, 30.0],
                      [100.0, 200.0, 300.0]])

numpy_arr

array([[  1.,   2.,   3.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [ ]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [ ]:
type(tensor_from_numpy)

torch.Tensor

In [ ]:
tensor_from_numpy[0] = 1
tensor_from_numpy

tensor([[  1.,   1.,   1.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [ ]:
numpy_arr

array([[  1.,   1.,   1.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [ ]:
np_array_one = np.array([4, 8])
np_array_one

array([4, 8])

In [ ]:
tensor_from_array_one = torch.as_tensor(np_array_one)
tensor_from_array_one

tensor([4, 8])

In [ ]:
np_array_one[1] = 5
np_array_one

array([4, 5])

In [ ]:
tensor_from_array_one

tensor([4, 5])

In [ ]:
np_array_two = np.array([2, 2])
np_array_two

array([2, 2])

In [ ]:
tensor_from_array_two = torch.tensor(np_array_two)
tensor_from_array_two

tensor([2, 2])

In [ ]:
np_array_two[1] = 4
np_array_two

array([2, 4])

In [ ]:
tensor_from_array_two

tensor([2, 2])