<a href="https://colab.research.google.com/github/shazzad-hasan/practice-deep-learning-with-pytorch/blob/main/foundation_of_pytorch/cuda_semantics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
torch.cuda.init()

In [ ]:
torch.cuda.current_device()

0

In [ ]:
torch.cuda.device_count()

1

In [ ]:
torch.cuda.memory_allocated()

0

In [ ]:
torch.cuda.memory_cached()

/usr/local/lib/python3.7/dist-packages/torch/cuda/memory.py:393: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  FutureWarning)


0

In [ ]:
cuda = torch.device('cuda')
cuda

device(type='cuda')

In [ ]:
cuda0 = torch.device('cuda:0')
cuda1 = torch.device('cuda:1')
cuda2 = torch.device('cuda:2')

cuda0, cuda1, cuda2

(device(type='cuda', index=0),
 device(type='cuda', index=1),
 device(type='cuda', index=2))

In [ ]:
x = torch.tensor([10., 20.])
x

tensor([10., 20.])

In [ ]:
x_default = torch.tensor([10., 20.], device=cuda)

x_default

tensor([10., 20.], device='cuda:0')

In [ ]:
x0 = torch.tensor([10., 20.], device=cuda0)
x0

tensor([10., 20.], device='cuda:0')

In [ ]:
x1 = torch.tensor([10., 20.], device=cuda1)
x1

RuntimeError: ignored

In [ ]:
y = x.cuda()
y

tensor([10., 20.], device='cuda:0')

In [ ]:
y0 = x0.cuda()
y0

tensor([10., 20.], device='cuda:0')

In [ ]:
with torch.cuda.device(0):
  a = torch.tensor([10., 20.])
  a0 = torch.tensor([10., 20.], device=cuda0)
  a1 = torch.tensor([10., 20.], device=cuda)

In [ ]:
a

tensor([10., 20.])

In [ ]:
a0

tensor([10., 20.], device='cuda:0')

In [ ]:
a1

tensor([10., 20.], device='cuda:0')

In [ ]:
b1 = a0.to(device=cuda0)
b1

tensor([10., 20.], device='cuda:0')

In [ ]:
sum_a = a + a0
sum_a

RuntimeError: ignored

In [ ]:
sum_a = a0 + a1
sum_a

tensor([20., 40.], device='cuda:0')

In [ ]:
torch.cuda.memory_allocated()

3072

In [ ]:
torch.cuda.memory_cached()

/usr/local/lib/python3.7/dist-packages/torch/cuda/memory.py:393: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  FutureWarning)


2097152

In [ ]:
torch.cuda.empty_cache()

In [ ]:
torch.cuda.memory_cached()

/usr/local/lib/python3.7/dist-packages/torch/cuda/memory.py:393: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  FutureWarning)


2097152

In [ ]:
preserve_context = x.new_full([2,2], fill_value=1.1)
preserve_context

tensor([[1.1000, 1.1000],
        [1.1000, 1.1000]])