<a href="https://colab.research.google.com/github/shazzad-hasan/building_deep_learning_solutions_with_pytorch/blob/main/foundation_of_pytorch/PyTorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

print(torch.__version__)

1.12.0+cu113


In [2]:
torch.get_default_dtype()

torch.float32

In [3]:
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()

torch.float64

In [4]:
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [5]:
torch.is_tensor(tensor_arr)

True

In [6]:
torch.numel(tensor_arr)

6

In [7]:
tensor_uninitialized = torch.Tensor(2,2)
tensor_uninitialized

tensor([[3.6574e-316, 1.7786e-322],
        [ 3.0000e+00,  2.2367e-46]])

In [8]:
tensor_initialized = torch.rand(2,2)
tensor_initialized

tensor([[0.1085, 0.8821],
        [0.4447, 0.5544]])

In [9]:
tensor_int = torch.tensor([5,3]).type(torch.IntTensor)
tensor_int

tensor([5, 3], dtype=torch.int32)

In [10]:
tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

In [11]:
tensor_float = torch.tensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

In [12]:
tensor_fill = torch.full((2,6), fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

In [13]:
tensor_of_ones = torch.ones([2,4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [14]:
tensor_of_zeros = torch.zeros_like(tensor_of_ones)
tensor_of_zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [15]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [25]:
i = torch.tensor([[0,1,1], 
                  [2,2,0]])
v = torch.tensor([5,6,7], dtype=torch.float32)
sparse_tensor = torch.sparse_coo_tensor(i, v, [2,5])
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([5., 6., 7.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

In [26]:
initial_tensor = torch.rand(2,3)
initial_tensor

tensor([[0.8495, 0.3344, 0.3670],
        [0.6078, 0.1497, 0.3976]])

In [27]:
initial_tensor.fill_(10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [28]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [29]:
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [30]:
initial_tensor.add_(8)
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [31]:
new_tensor.sqrt()
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [32]:
x = torch.linspace(start=0.1, end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [33]:
tensor_chunk = torch.chunk(x, 3, 0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [34]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3.0, 4.0, 5.0])

torch.cat((tensor1, tensor2, tensor3), 0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [35]:
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 21]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [36]:
random_tensor[0, 1]

tensor(8.)

In [37]:
random_tensor[1:, 1:]

tensor([[ 5.,  6.],
        [ 2., 21.]])

In [38]:
random_tensor.size()

torch.Size([3, 3])

In [39]:
resized_tensor = random_tensor.view(9)
resized_tensor

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])

In [41]:
resized_tensor.size()

torch.Size([9])

In [42]:
random_tensor[2,2] = 100.0
resized_tensor

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

In [43]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [45]:
random_tensor.shape

torch.Size([3, 3])

In [47]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, 2)
tensor_unsqueeze

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [48]:
tensor_unsqueeze.shape

torch.Size([3, 3, 1])

In [49]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [50]:
tensor_transpose = torch.transpose(initial_tensor, 0, 1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

In [51]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)

In [52]:
sorted_tensor

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

In [53]:
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [54]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000], dtype=torch.float32)

In [55]:
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000], dtype=torch.float32)

In [56]:
rand1 = torch.abs(torch.randn(2,3))
rand2 = torch.abs(torch.randn(2,3))

add1 = rand1 + rand2
add1

tensor([[1.0141, 2.5752, 1.6105],
        [1.7875, 2.4736, 1.3036]])

In [57]:
add2 = torch.add(rand1, rand2)
add2

tensor([[1.0141, 2.5752, 1.6105],
        [1.7875, 2.4736, 1.3036]])

In [58]:
tensor = torch.Tensor([[-1, -2, -3],
                       [1, 2, 3]])

tensor_div = torch.div(tensor, tensor + 0.3)
tensor_div

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])

In [59]:
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

In [61]:
tensor

tensor([[-1., -2., -3.],
        [ 1.,  2.,  3.]])

In [60]:
tensor_clamp = torch.clamp(tensor, min=-0.2, max=2)
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

In [62]:
t1 = torch.Tensor([1, 2])
t2 = torch.Tensor([10, 20])

dot_product = torch.dot(t1, t2)
dot_product

tensor(50.)

In [64]:
matrix = torch.Tensor([[1,2,3],
                       [4,5,6]])

vector = torch.Tensor([0, 1, 2])

matrix_vector = torch.mv(matrix, vector)
matrix_vector

tensor([ 8., 17.])

In [65]:
another_matrix = torch.Tensor([[10, 30],
                       [20, 0],
                       [0, 50]])

matrix_mul = torch.mm(matrix, another_matrix)
matrix_mul

tensor([[ 50., 180.],
        [140., 420.]])

In [66]:
torch.argmax(matrix_mul, dim=1)

tensor([1, 1])

In [67]:
torch.argmin(matrix_mul, dim=0)

tensor([0, 0])